### ISSUE TITLE
Default background dependent on dark mode settings

### ISSUE THREAD

**Issue by HakureiKion** [bluecaret/carettab#178]
I am currently using Firefox 82.0.2 (64-bit) on Windows 10 1909 and 2004.

When Firefox is in Dark Mode (following the system settings), the page still flashes white when a new tab is opened. 

It can be found in the Inspect Elements that the default body background is still white, even if I set `#000000` for the custom background, and `#FFFFFF` for the foreground:
```
body {
    margin: 0;
    position: relative;
    background: #fff;
    font-family: "Open Sans",sans-serif;
    font-size: 1.6rem;
    color: #000;
    overflow: hidden;
}
```

If the extension can follow Firefox's dark mode settings, and use the dark background as the default one, it would drastically improve the overall experience!

And it would be great if users are allowed to choose which mode (light/dark/depends-on-system-settings) the extension uses!

Thank you for developing such a great extension!

**Comment by bluecaret** [comment]
I unfortunately do not have the ability to fix this. I can only affect things after the extension has loaded, I have no access to what happens before loading and therefore am unable to change this. It is actually a failure of all the browsers that they still default to a white background even for dark mode before the extension has time to load.

Thank you for your support!

**Comment by bluecaret** [comment]
Whoops I'm sorry, bit tired right now when I looked at this and was thinking of it wrong. I re-read your info and you might have something there, reopening and marking as a bug 👍

**Comment by bluecaret** [comment]
Fixed in version 3.1.0

**Comment by DrBones** [comment]
Sorry to comment on a closed issue, however the fix does not seem to work for me. I still see bright white flashes although my Firefox theme is dark. It might be related to the macOS theme since I actually get black flashes when using a bright carettab background. Is it maybe not only picking up on the firefox theme but the OS theme as well? 

I could not however get the bright flash to disappear with any combination of bright, dark and auto/default theme in macOS and Firefox. The media queries look fine though, for all I can see, I am no expert on that matter. 

    @media (prefers-color-scheme: dark) {
      body {
        background: #000;
        color: #bbb;
      }
    }

    @media (prefers-color-scheme: light) {
      body {
        background: #fff;
        color: #555;
      }
    }

    #splashScreen {
      opacity: 1;
      transition: opacity .3s ease-in-out;
      position: fixed;
      height: 100vh;
      width: 100vw;
      top: 0;
      left: 0;
      z-index: 99999;
    }
    #splashScreen.loaded {
      opacity: 0;
    }

Firefox 85.0, macOS 10.15.7

Is there anything else I can try or take a look at, with no custom tab the background is dark so I suspect some interaction with the extension, or should I open a new issue?

Apart from that, awesome little extension though, I enjoy opening tabs even more :)
